{
  "formatVersion": "1.1",
  "component": {
    "group": "org.mcphackers",
    "module": "launchwrapper",
    "version": "1.0-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 5,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "launchwrapper-1.0-snapshot.jar",
          "url": "launchwrapper-1.0-snapshot.jar",
          "size": 116012,
          "sha512": "42d37ff597a24853b066a573c5eddf73bf1e7b440979a04f6d9882e8aa3a6831494a96f5fac7eef41e73f4717a9672ccb17efed235c0e579154c639558caf978",
          "sha256": "25960c8fd7d15cefc326b71777e28cc7121f43d35e0698664d5aea2f80a44c25",
          "sha1": "289b3d61fc0cc56cd11b4ed46f74ee77355b6f7c",
          "md5": "7d22ef065da46ce9460bf211da3c5167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 5,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": null,
          "module": "discord-rpc-1.6.2"
        },
        {
          "group": "org.mcphackers.rdi",
          "module": "rdi",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.3"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20230311"
          }
        }
      ],
      "files": [
        {
          "name": "launchwrapper-1.0-snapshot.jar",
          "url": "launchwrapper-1.0-snapshot.jar",
          "size": 116012,
          "sha512": "42d37ff597a24853b066a573c5eddf73bf1e7b440979a04f6d9882e8aa3a6831494a96f5fac7eef41e73f4717a9672ccb17efed235c0e579154c639558caf978",
          "sha256": "25960c8fd7d15cefc326b71777e28cc7121f43d35e0698664d5aea2f80a44c25",
          "sha1": "289b3d61fc0cc56cd11b4ed46f74ee77355b6f7c",
          "md5": "7d22ef065da46ce9460bf211da3c5167"
        }
      ]
    }
  ]
}
